### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by hitchhiker** [makkus/docker-seafile#10]
Hi,

I've migrated the images to a new machine, and am moving the local filesystem - how can i recreate the docker ps (containers etc) , will running .first-time-setup work? or is there a better method?

Cheers,
Frank.

**Comment by makkus** [comment]
In theory, having the volumes in place (using your old docker-compose.yml and potentially changing the local paths) and doing a

```
docker-compose build
docker-compose up -d
```

should be enough. I haven't tried that for a while yet, so can't guarantee it'll work. Make sure you use the same versions of seafile on the original and new containers.

I'm looking into re-writing this whole thing at the moment, because seafile improved the way it needs to be deployed since I first wrote all this. That should result in a simpler management of those containers in the future. Won't help you at the moment though, unfortunately.

**Comment by hitchhiker** [comment]
Thanks Makkus - btw: this dockerfile has been extremely helpful - thanks!

**Comment by makkus** [comment]
Thanks! Good to hear!
