### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by umiddelb** [makkus/docker-seafile#4]
Hi Markus,

I'm playing around with docker on the ARM platform for a while and want to put seafile into a Docker container. Have you ever considered to build a seafile image on top of [phusion/baseimage](https://github.com/phusion/baseimage-docker). This might help to skip to docker compose dependency.

Have you ever tried to port seafile to ubuntu on ARM? I've tried it but ended in a totally messed up userland (that was the point I've decided to learn Docker first ;).

Kind regards
Uli

**Comment by makkus** [comment]
The seafile container is currently built using phusion/baseimage (check out the Dockerfile in the seafile container). Actually I've got half a plan to get away from phusion and move to a vanilla Debian/Ubuntu baseimage, for several reasons. Not a priority at the moment though.

There are other seafile docker containers out there that don't use docker-compose (e.g. https://github.com/JensErat/docker-seafile), but I for one explicitly wanted it, because I like the separation of the different modules it provides (data, db, seafile, webserver). Makes it easy to fire up different configurations (e.g. some using nginx, some apache because shibboleth is a requirement, some community version, some pro version). So, no, I won't try to do without docker-compose :-)

As far as I'm aware there is a seafile image for the Raspberry Pi, so if I were you I'd use this as a template. Even if you get Docker to run on ARM, you won't be able to use images that were build for x86/x64, that's not how Docker works.
